// <auto-generated />
using System;
using Accounting.Persistence.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Accounting.Persistence.EF.Migrations
{
    [DbContext(typeof(AccountingDbContext))]
    partial class AccountingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.HasSequence("AccountSeq");

            modelBuilder.HasSequence("BankBranchSeq");

            modelBuilder.HasSequence("BankSeq");

            modelBuilder.HasSequence("BranchSeq");

            modelBuilder.HasSequence("CostCenterSeq");

            modelBuilder.HasSequence("FiscalYearSeq");

            modelBuilder.HasSequence("FloatAccountGroupSeq");

            modelBuilder.HasSequence("FloatAccountSeq");

            modelBuilder.HasSequence("TransactionSeq");

            modelBuilder.HasSequence("VoucherSeq");

            modelBuilder.Entity("Accounting.Domain.Model.Account.Account", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("AccountDiscriminator")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("AccountNature")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ActionTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long>("ActionUserId")
                        .HasColumnType("bigint");

                    b.Property<int>("Code")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreateOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("EnglishName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("EnglishName");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("Name");

                    b.Property<int>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.ToTable("Accounts");

                    b.HasDiscriminator<string>("AccountDiscriminator").HasValue("Account");
                });

            modelBuilder.Entity("Accounting.Domain.Model.AccountTemplates.AccountTemplate", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ActionTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long>("ActionUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreateOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("EventName")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("PersianName")
                        .HasColumnType("text");

                    b.Property<int>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.ToTable("AccountTemplates");
                });

            modelBuilder.Entity("Accounting.Domain.Model.BankBranches.BankBranch", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ActionTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long>("ActionUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("Address");

                    b.Property<long>("BankId")
                        .HasColumnType("bigint")
                        .HasColumnName("BankId");

                    b.Property<string>("BranchCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("BranchCode");

                    b.Property<long>("CityId")
                        .HasColumnType("bigint")
                        .HasColumnName("CityId");

                    b.Property<string>("CityName")
                        .HasColumnType("text")
                        .HasColumnName("CityName");

                    b.Property<DateTime>("CreateOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("EnglishName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("EnglishName");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Name");

                    b.Property<int>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<string>("SwiftCode")
                        .HasColumnType("text")
                        .HasColumnName("SwiftCode");

                    b.Property<string>("Tell")
                        .HasColumnType("text")
                        .HasColumnName("Tell");

                    b.HasKey("Id");

                    b.ToTable("BankBranches");
                });

            modelBuilder.Entity("Accounting.Domain.Model.Banks.Bank", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ActionTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long>("ActionUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("BranchCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("BranchCode");

                    b.Property<DateTime>("CreateOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("EnglishName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("EnglishName");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Name");

                    b.Property<int>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<string>("SwiftCode")
                        .HasColumnType("text")
                        .HasColumnName("SwiftCode");

                    b.Property<string>("WebSiteUrl")
                        .HasColumnType("text")
                        .HasColumnName("WebSiteUrl");

                    b.HasKey("Id");

                    b.ToTable("Banks");
                });

            modelBuilder.Entity("Accounting.Domain.Model.Branches.Branch", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("AbbreviationChar")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ActionTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long>("ActionUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreateOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("EnglishName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("ExternalSystemId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("Language")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<bool>("UseGregorianCalendar")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("Branches");
                });

            modelBuilder.Entity("Accounting.Domain.Model.CostCenters.CostCenter", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ActionTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long>("ActionUserId")
                        .HasColumnType("bigint");

                    b.Property<long?>("BranchId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreateOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("EnglishName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.ToTable("CostCenters");
                });

            modelBuilder.Entity("Accounting.Domain.Model.FiscalYear.FiscalYear", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ActionTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long>("ActionUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreateOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("EndDate");

                    b.Property<string>("EnglishName")
                        .HasColumnType("text")
                        .HasColumnName("EnglishName");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("Name");

                    b.Property<int>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("StartDate");

                    b.HasKey("Id");

                    b.ToTable("FiscalYears");
                });

            modelBuilder.Entity("Accounting.Domain.Model.FloatAccount.FloatAccount", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ActionTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long>("ActionUserId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Budget")
                        .HasColumnType("numeric")
                        .HasColumnName("Budget");

                    b.Property<int>("Code")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreateOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("Description");

                    b.Property<string>("EnglishName")
                        .HasColumnType("text")
                        .HasColumnName("EnglishName");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("Name");

                    b.Property<long?>("ParentFloatAccountId")
                        .HasColumnType("bigint")
                        .HasColumnName("ParentFloatAccountId");

                    b.Property<int>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.ToTable("FloatAccounts");
                });

            modelBuilder.Entity("Accounting.Domain.Model.FloatAccountGroups.FloatAccountGroup", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long>("AccountId")
                        .HasColumnType("bigint")
                        .HasColumnName("AccountId");

                    b.Property<DateTime?>("ActionTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long>("ActionUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreateOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long>("FloatAccountId")
                        .HasColumnType("bigint")
                        .HasColumnName("FloatAccountId");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.ToTable("FloatAccountGroups");
                });

            modelBuilder.Entity("Accounting.Domain.Model.TradingUnits.TradingUnit", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ActionTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long>("ActionUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreateOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("EnglishName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("EnglishName");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<long?>("LegacyId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("Name");

                    b.Property<int>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("integer");

                    b.Property<int>("TradingUnitType")
                        .HasColumnType("integer")
                        .HasColumnName("TradingUnitType");

                    b.HasKey("Id");

                    b.ToTable("TradingUnits");
                });

            modelBuilder.Entity("Accounting.Domain.Model.Transactions.Transaction", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ActionTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long>("ActionUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreateOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRegistered")
                        .HasColumnType("boolean")
                        .HasColumnName("IsRegistered");

                    b.Property<int>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("Accounting.Domain.Model.Transactions.TransactionReferences.TransactionReference", b =>
                {
                    b.Property<long>("TransactionId")
                        .HasColumnType("bigint");

                    b.Property<long>("ActionUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("ActionUserId");

                    b.Property<DateTime>("FormalDateTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("FormalDateTime");

                    b.Property<long>("IssuerBranchId")
                        .HasColumnType("bigint")
                        .HasColumnName("IssuerBranchId");

                    b.Property<long>("ReferenceId")
                        .HasColumnType("bigint")
                        .HasColumnName("ReferenceId");

                    b.Property<string>("UserName")
                        .HasColumnType("text")
                        .HasColumnName("UserName");

                    b.HasKey("TransactionId");

                    b.ToTable("TransactionReferences");
                });

            modelBuilder.Entity("Accounting.Domain.Model.Voucher.Voucher", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ActionTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long>("ActionUserId")
                        .HasColumnType("bigint");

                    b.Property<long>("ApprovementUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("ApprovementUserId");

                    b.Property<DateTime>("CreateOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("Description");

                    b.Property<long>("DisplayOrder")
                        .HasColumnType("bigint")
                        .HasColumnName("DisplayOrder");

                    b.Property<DateTime>("FormalDateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<long>("IssuedBranchId")
                        .HasColumnType("bigint")
                        .HasColumnName("IssuedBranchId");

                    b.Property<int>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<long>("VoucherTypeId")
                        .HasColumnType("bigint")
                        .HasColumnName("VoucherTypeId");

                    b.HasKey("Id");

                    b.ToTable("Vouchers");
                });

            modelBuilder.Entity("Accounting.Domain.Model.Voucher.VoucherStatuses.VoucherStatus", b =>
                {
                    b.Property<long>("VoucherId")
                        .HasColumnType("bigint");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("VoucherId");

                    b.ToTable("VoucherStatuses");

                    b.HasDiscriminator<string>("Discriminator").HasValue("VoucherStatus");
                });

            modelBuilder.Entity("Accounting.Persistence.EF.ProcessMessages.AccountingProcessedMessage", b =>
                {
                    b.Property<Guid>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("UUID")
                        .HasColumnName("eventid");

                    b.HasKey("EventId");

                    b.ToTable("accountingprocessedmessages");
                });

            modelBuilder.Entity("Accounting.Domain.Model.Account.AccountGroups.AccountGroup", b =>
                {
                    b.HasBaseType("Accounting.Domain.Model.Account.Account");

                    b.Property<int>("AccountType")
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue("AccountGroup");
                });

            modelBuilder.Entity("Accounting.Domain.Model.Account.DetailedAccounts.DetailedAccount", b =>
                {
                    b.HasBaseType("Accounting.Domain.Model.Account.Account");

                    b.Property<long?>("ParentId")
                        .HasColumnType("bigint");

                    b.Property<long?>("SubsidiaryAccountId")
                        .HasColumnType("bigint");

                    b.HasDiscriminator().HasValue("DetailedAccount");
                });

            modelBuilder.Entity("Accounting.Domain.Model.Account.GeneralAccounts.GeneralAccount", b =>
                {
                    b.HasBaseType("Accounting.Domain.Model.Account.Account");

                    b.Property<long?>("AccountGroupId")
                        .HasColumnType("bigint");

                    b.HasDiscriminator().HasValue("GeneralAccount");
                });

            modelBuilder.Entity("Accounting.Domain.Model.Account.SubsidiaryAccounts.SubsidiaryAccount", b =>
                {
                    b.HasBaseType("Accounting.Domain.Model.Account.Account");

                    b.Property<long?>("GeneralAccountId")
                        .HasColumnType("bigint");

                    b.HasDiscriminator().HasValue("SubsidiaryAccount");
                });

            modelBuilder.Entity("Accounting.Domain.Model.Transactions.TransactionReferences.InvoiceReference", b =>
                {
                    b.HasBaseType("Accounting.Domain.Model.Transactions.TransactionReferences.TransactionReference");

                    b.Property<long>("DestinationTradingUnitId")
                        .HasColumnType("bigint")
                        .HasColumnName("DestinationTradingUnitId");

                    b.Property<decimal>("Discount")
                        .HasColumnType("numeric")
                        .HasColumnName("Discount");

                    b.Property<decimal>("Fee")
                        .HasColumnType("numeric")
                        .HasColumnName("Fee");

                    b.Property<long?>("FeeId")
                        .HasColumnType("bigint")
                        .HasColumnName("FeeId");

                    b.Property<long?>("FeeTradingUnitId")
                        .HasColumnType("bigint")
                        .HasColumnName("FeeTradingUnitId");

                    b.Property<decimal>("Rate")
                        .HasColumnType("numeric")
                        .HasColumnName("Rate");

                    b.Property<bool>("RateReverseCalculation")
                        .HasColumnType("boolean")
                        .HasColumnName("RateReverseCalculation");

                    b.Property<decimal>("ReceivableTotal")
                        .HasColumnType("numeric")
                        .HasColumnName("ReceivableTotal");

                    b.Property<long>("SourceTradingUnitId")
                        .HasColumnType("bigint")
                        .HasColumnName("SourceTradingUnitId");

                    b.ToTable("InvoiceReferences");
                });

            modelBuilder.Entity("Accounting.Domain.Model.Transactions.TransactionReferences.PaymentRequestReference", b =>
                {
                    b.HasBaseType("Accounting.Domain.Model.Transactions.TransactionReferences.TransactionReference");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric")
                        .HasColumnName("Amount");

                    b.Property<long>("BusinessPartnerId")
                        .HasColumnType("bigint")
                        .HasColumnName("BusinessPartnerId");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("Description");

                    b.Property<decimal>("Fee")
                        .HasColumnType("numeric")
                        .HasColumnName("Fee");

                    b.Property<long?>("FeeTradingUnitId")
                        .HasColumnType("bigint")
                        .HasColumnName("FeeTradingUnitId");

                    b.Property<long>("TradingUnitId")
                        .HasColumnType("bigint")
                        .HasColumnName("TradingUnitId");

                    b.ToTable("PaymentRequestReferences");
                });

            modelBuilder.Entity("Accounting.Domain.Model.Voucher.VoucherStatuses.VoucherApproved", b =>
                {
                    b.HasBaseType("Accounting.Domain.Model.Voucher.VoucherStatuses.VoucherStatus");

                    b.HasDiscriminator().HasValue("VoucherApproved");
                });

            modelBuilder.Entity("Accounting.Domain.Model.Voucher.VoucherStatuses.VoucherPending", b =>
                {
                    b.HasBaseType("Accounting.Domain.Model.Voucher.VoucherStatuses.VoucherStatus");

                    b.HasDiscriminator().HasValue("VoucherPending");
                });

            modelBuilder.Entity("Accounting.Domain.Model.Voucher.VoucherStatuses.VoucherRejected", b =>
                {
                    b.HasBaseType("Accounting.Domain.Model.Voucher.VoucherStatuses.VoucherStatus");

                    b.HasDiscriminator().HasValue("VoucherRejected");
                });

            modelBuilder.Entity("Accounting.Domain.Model.AccountTemplates.AccountTemplate", b =>
                {
                    b.OwnsMany("Accounting.Domain.Model.AccountTemplates.AccountTemplateItem", "AccountTemplateItems", b1 =>
                        {
                            b1.Property<long>("AccountTemplateId")
                                .HasColumnType("bigint");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                            b1.Property<long?>("DetailedAccountId")
                                .HasColumnType("bigint")
                                .HasColumnName("DetailedAccountId");

                            b1.Property<int>("PropertyInfo")
                                .HasColumnType("integer")
                                .HasColumnName("PropertyInfo");

                            b1.Property<long>("SubsidiaryAccountId")
                                .HasColumnType("bigint")
                                .HasColumnName("SubsidiaryAccountId");

                            b1.Property<int>("TypeOfDebitCredit")
                                .HasColumnType("integer")
                                .HasColumnName("TypeOfDebitCredit");

                            b1.HasKey("AccountTemplateId", "Id");

                            b1.ToTable("AccountTemplateItems");

                            b1.WithOwner()
                                .HasForeignKey("AccountTemplateId");
                        });

                    b.Navigation("AccountTemplateItems");
                });

            modelBuilder.Entity("Accounting.Domain.Model.FloatAccount.FloatAccount", b =>
                {
                    b.OwnsOne("Accounting.Domain.Model.FloatAccount.AccountReferenceInfo", "AccountReferenceInfo", b1 =>
                        {
                            b1.Property<long>("FloatAccountId")
                                .HasColumnType("bigint");

                            b1.Property<long>("AccountReferenceId")
                                .HasColumnType("bigint")
                                .HasColumnName("AccountReferenceId");

                            b1.Property<int>("AccountReferenceType")
                                .HasColumnType("integer")
                                .HasColumnName("AccountReferenceType");

                            b1.Property<string>("LegacyAccountSystemReferenceId")
                                .HasColumnType("text")
                                .HasColumnName("LegacyAccountSystemReferenceId");

                            b1.HasKey("FloatAccountId");

                            b1.ToTable("FloatAccounts");

                            b1.WithOwner()
                                .HasForeignKey("FloatAccountId");
                        });

                    b.Navigation("AccountReferenceInfo");
                });

            modelBuilder.Entity("Accounting.Domain.Model.Transactions.Transaction", b =>
                {
                    b.OwnsOne("Accounting.Domain.Model.Transactions.OwnerInformation", "OwnerInformation", b1 =>
                        {
                            b1.Property<long>("TransactionId")
                                .HasColumnType("bigint");

                            b1.Property<string>("Name")
                                .HasColumnType("text")
                                .HasColumnName("Name");

                            b1.Property<long>("OwnerId")
                                .HasColumnType("bigint")
                                .HasColumnName("OwnerId");

                            b1.Property<int>("OwnerType")
                                .HasColumnType("integer")
                                .HasColumnName("OwnerType");

                            b1.HasKey("TransactionId");

                            b1.ToTable("Transactions");

                            b1.WithOwner()
                                .HasForeignKey("TransactionId");
                        });

                    b.OwnsMany("Accounting.Domain.Model.Transactions.TransactionItem", "TransactionItems", b1 =>
                        {
                            b1.Property<long>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint")
                                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric")
                                .HasColumnName("Amount");

                            b1.Property<long>("TransactionId")
                                .HasColumnType("bigint");

                            b1.Property<int>("TransactionItemReference")
                                .HasColumnType("integer")
                                .HasColumnName("TransactionItemReference");

                            b1.Property<int>("TransactionItemType")
                                .HasColumnType("integer")
                                .HasColumnName("TransactionItemType");

                            b1.HasKey("Id");

                            b1.HasIndex("TransactionId");

                            b1.ToTable("TransactionItems");

                            b1.WithOwner()
                                .HasForeignKey("TransactionId");
                        });

                    b.Navigation("OwnerInformation");

                    b.Navigation("TransactionItems");
                });

            modelBuilder.Entity("Accounting.Domain.Model.Transactions.TransactionReferences.TransactionReference", b =>
                {
                    b.HasOne("Accounting.Domain.Model.Transactions.Transaction", null)
                        .WithOne("TransactionReference")
                        .HasForeignKey("Accounting.Domain.Model.Transactions.TransactionReferences.TransactionReference", "TransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Accounting.Domain.Model.Voucher.Voucher", b =>
                {
                    b.OwnsMany("Accounting.Domain.Model.Voucher.VoucherItems.VoucherItem", "VoucherItems", b1 =>
                        {
                            b1.Property<long>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint")
                                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                            b1.Property<DateTime?>("ActionTime")
                                .HasColumnType("timestamp without time zone");

                            b1.Property<long>("ActionUserId")
                                .HasColumnType("bigint");

                            b1.Property<long>("BranchTradingUnitId")
                                .HasColumnType("bigint");

                            b1.Property<long>("DisplayOrder")
                                .HasColumnType("bigint")
                                .HasColumnName("DisplayOrder");

                            b1.Property<long?>("FirstCostCenterId")
                                .HasColumnType("bigint")
                                .HasColumnName("FirstCostCenterId");

                            b1.Property<long?>("SecondCostCenterId")
                                .HasColumnType("bigint")
                                .HasColumnName("SecondCostCenterId");

                            b1.Property<long>("TradingUnitId")
                                .HasColumnType("bigint")
                                .HasColumnName("TradingUnitId");

                            b1.Property<long>("VoucherId")
                                .HasColumnType("bigint");

                            b1.HasKey("Id");

                            b1.HasIndex("VoucherId");

                            b1.ToTable("VoucherItems");

                            b1.WithOwner()
                                .HasForeignKey("VoucherId");

                            b1.OwnsOne("Accounting.Domain.Model.Voucher.VoucherItems.ReferenceInfo", "ReferenceInfo", b2 =>
                                {
                                    b2.Property<long>("VoucherItemId")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("bigint")
                                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                                    b2.Property<long>("ReferenceId")
                                        .HasColumnType("bigint")
                                        .HasColumnName("ReferenceId");

                                    b2.Property<int>("ReferenceType")
                                        .HasColumnType("integer")
                                        .HasColumnName("ReferenceType");

                                    b2.HasKey("VoucherItemId");

                                    b2.ToTable("VoucherItems");

                                    b2.WithOwner()
                                        .HasForeignKey("VoucherItemId");
                                });

                            b1.OwnsOne("Accounting.Domain.Model.Voucher.VoucherItems.VoucherAccountTemplateItem", "VoucherAccountTemplateItem", b2 =>
                                {
                                    b2.Property<long>("VoucherItemId")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("bigint")
                                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                                    b2.Property<long?>("DetailedAccountId")
                                        .HasColumnType("bigint")
                                        .HasColumnName("DetailedAccountId");

                                    b2.Property<long?>("FloatAccountId")
                                        .HasColumnType("bigint")
                                        .HasColumnName("FloatAccountId");

                                    b2.Property<long>("SubsidiaryAccountId")
                                        .HasColumnType("bigint")
                                        .HasColumnName("SubsidiaryAccountId");

                                    b2.Property<int>("TypeOfDebitCredit")
                                        .HasColumnType("integer")
                                        .HasColumnName("TypeOfDebitCredit");

                                    b2.HasKey("VoucherItemId");

                                    b2.ToTable("VoucherItems");

                                    b2.WithOwner()
                                        .HasForeignKey("VoucherItemId");
                                });

                            b1.OwnsOne("Accounting.Domain.Model.Voucher.VoucherItems.VoucherItemAmounts", "VoucherItemAmounts", b2 =>
                                {
                                    b2.Property<long>("VoucherItemId")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("bigint")
                                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                                    b2.Property<decimal>("CreditAmount")
                                        .HasColumnType("numeric")
                                        .HasColumnName("CreditAmount");

                                    b2.Property<decimal>("DebitAmount")
                                        .HasColumnType("numeric")
                                        .HasColumnName("DebitAmount");

                                    b2.Property<decimal>("ExchangeCreditAmount")
                                        .HasColumnType("numeric")
                                        .HasColumnName("ExchangeCreditAmount");

                                    b2.Property<decimal>("ExchangeDebitAmount")
                                        .HasColumnType("numeric")
                                        .HasColumnName("ExchangeDebitAmount");

                                    b2.HasKey("VoucherItemId");

                                    b2.ToTable("VoucherItems");

                                    b2.WithOwner()
                                        .HasForeignKey("VoucherItemId");
                                });

                            b1.Navigation("ReferenceInfo");

                            b1.Navigation("VoucherAccountTemplateItem");

                            b1.Navigation("VoucherItemAmounts");
                        });

                    b.Navigation("VoucherItems");
                });

            modelBuilder.Entity("Accounting.Domain.Model.Voucher.VoucherStatuses.VoucherStatus", b =>
                {
                    b.HasOne("Accounting.Domain.Model.Voucher.Voucher", null)
                        .WithOne("Status")
                        .HasForeignKey("Accounting.Domain.Model.Voucher.VoucherStatuses.VoucherStatus", "VoucherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Accounting.Domain.Model.Transactions.TransactionReferences.InvoiceReference", b =>
                {
                    b.HasOne("Accounting.Domain.Model.Transactions.TransactionReferences.TransactionReference", null)
                        .WithOne()
                        .HasForeignKey("Accounting.Domain.Model.Transactions.TransactionReferences.InvoiceReference", "TransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Accounting.Domain.Model.Transactions.TransactionReferences.PaymentRequestReference", b =>
                {
                    b.HasOne("Accounting.Domain.Model.Transactions.TransactionReferences.TransactionReference", null)
                        .WithOne()
                        .HasForeignKey("Accounting.Domain.Model.Transactions.TransactionReferences.PaymentRequestReference", "TransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Accounting.Domain.Model.Transactions.Transaction", b =>
                {
                    b.Navigation("TransactionReference");
                });

            modelBuilder.Entity("Accounting.Domain.Model.Voucher.Voucher", b =>
                {
                    b.Navigation("Status");
                });
#pragma warning restore 612, 618
        }
    }
}
